title: Rapella Art
home_title: Digital & Fine Art by Madi Rapella
logo: /assets/img/site/logo.png
permalink: /:slug

navbar:
  - name: Home
    link: /
  - name: Digital Art
    link: /digital-art
  - name: Fine Art
    link: /fine-art
  - name: Contact & Pricing
    link: /contact
  - name: About the Artist
    link: /about
  - name: Store
    link: https://shop.rapellaart.com/

# Social media links
social:
  - name: Facebook
    icon: fab fa-facebook
    url: https://www.facebook.com/madi.rapella.3
  - name: Instagram
    icon: fab fa-instagram
    url: https://instagram.com/rapellaart
  - name: LinkedIn
    icon: fab fa-linkedin-in
    url: https://www.linkedin.com/in/mrapella/
  - name: Email
    icon: fas fa-envelope
    url: mailto:mrapella@csumb.edu

# Projects
collections:
  pages:
    permalink: /:slug
    output: true
    
assets:
  img: /assets/img/
  css: /assets/css/
  js: /assets/js/
  files: assets/files/
    
# Project Settings
    
sass:
  style: compressed
  
# host: 0.0.0.0