title: Rapella Art
home_title: Digital & Fine Art by Madi Rapella
logo: /assets/img/site/logo.png
permalink: /:slug

cloudinary_url: "https://res.cloudinary.com/rapella/t_optimized"
store-open: false

menu:
  header:
    - url: /
      title: Home
    - url: /collections
      title: Collections
    - url: /about
      title: About the Artist
    - url: /statement
      title: Artist Statement
    - url: /pricing
      title: Commissions


# Social media links
social:
  - name: Facebook
    icon: fab fa-facebook
    url: https://www.facebook.com/madi.rapella.3
  - name: Instagram
    icon: fab fa-instagram
    url: https://instagram.com/rapellaart
  - name: LinkedIn
    icon: fab fa-linkedin-in
    url: https://www.linkedin.com/in/mrapella/
  - name: Email
    icon: fas fa-envelope
    url: mailto:mrapella@csumb.edu

# Projects
collections:
  pages:
    permalink: /:slug
    output: true
  art-collections:
    permalink: /collection/:slug
    output: true
    
assets:
  img: /assets/img/
  css: /assets/css/
  js: /assets/js/
  files: assets/files/
    
# Project Settings
    
sass:
  style: compressed
  
# host: 0.0.0.0